[package]
name = "commonware-fuzz"
version = "0.0.1"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
commonware-codec = { workspace = true }
libfuzzer-sys = { workspace = true }
bytes = { workspace = true }
arbitrary = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }

[[bin]]
name = "codec-roundtrip"
path = "fuzz_targets/codec_roundtrip.rs"
test = false
doc = false
bench = false